---
- name: RabbitMQ Server
  hosts: messaging
  sudo: yes
  vars_files:
    - ../../program_vars/rabbitmq

  tasks:
    - name: ensure rabbitmq-server packages are installed
      apt: pkg=rabbitmq-server force=yes

    - name: ensure rabbitmq management plugin is installed
      rabbitmq_plugin: names=rabbitmq_management state=enabled
      notify:
        - restart rabbitmq-server

    - name: ensure rabbitmq vhosts (nova) is existed
      rabbitmq_vhost: name={{rabbit_nova_vhost}} state=present

    - name: ensure rabbitmq vhosts (glance) is existed
      rabbitmq_vhost: name={{rabbit_glance_vhost}} state=present

    - name: ensure rabbitmq vhosts (cinder) is existed
      rabbitmq_vhost: name={{rabbit_cinder_vhost}} state=present

    - name: ensure rabbitmq vhosts (neutron) is existed
      rabbitmq_vhost: name={{rabbit_neutron_vhost}} state=present

    - name: ensure rabbitmq user (nova) is existed
      rabbitmq_user: >
           user={{rabbit_nova_user}}
           password={{rabbit_nova_password}}
           vhost={{rabbit_nova_vhost}}
           configure_priv=.*
           read_priv=.*
           write_priv=.*
           state=present

    - name: ensure rabbitmq user (glance) is existed
      rabbitmq_user: >
           user={{rabbit_glance_user}}
           password={{rabbit_glance_password}}
           vhost={{rabbit_glance_vhost}}
           configure_priv=.*
           read_priv=.*
           write_priv=.*
           state=present

    - name: ensure rabbitmq user (cinder) is existed
      rabbitmq_user: >
           user={{rabbit_cinder_user}}
           password={{rabbit_cinder_password}}
           vhost={{rabbit_cinder_vhost}}
           configure_priv=.*
           read_priv=.*
           write_priv=.*
           state=present

    - name: ensure rabbitmq user (neutron) is existed
      rabbitmq_user: >
           user={{rabbit_neutron_user}}
           password={{rabbit_neutron_password}}
           vhost={{rabbit_neutron_vhost}}
           configure_priv=.*
           read_priv=.*
           write_priv=.*
           state=present

    - name: ensure rabbitmq user (guest) is not existed
      rabbitmq_user: name=guest state=absent

  handlers:
    - name: restart rabbitmq-server
      service: name=rabbitmq-server state=restarted
