---
- name: OS Account(Compute frontend)
  hosts: frontend
  sudo: yes

  tasks:
    - name: ensure nova system group is present
      group: >
          name=nova
          gid=123
          system=yes
  
    - name: ensure nova system user is present
      user: >
          name=nova
          uid=123
          home=/var/lib/nova
          group=nova
          shell=/bin/false
          system=yes

    - name: ensure horizon system group is present
      group: >
          name=horizon
          gid=128
          system=yes
  
    - name: ensure horizon system user is present
      user: >
          name=horizon
          uid=128
          home=/usr/share/openstack-dashboard
          group=horizon
          shell=/bin/false
          system=yes

- name: OS Account(Compute Scheduler)
  hosts: compute_scheduler
  sudo: yes

  tasks:
    - name: ensure nova system group is present
      group: >
          name=nova
          gid=123
          system=yes

    - name: ensure nova system user is present
      user: >
          name=nova
          uid=123
          home=/var/lib/nova
          group=nova
          shell=/bin/false
          system=yes

- name: OS Account(Compute backend)
  hosts: compute_backend
  sudo: yes

  tasks:
    - name: ensure kvm system group is present
      group: >
          name=kvm
          gid=121
          system=yes

    - name: ensure libvirtd system group is present
      group: >
          name=libvirtd
          gid=122
          system=yes

    - name: ensure libvirt-qemu system user is present
      user: >
          name=libvirt-qemu
          uid=121
          home=/var/lib/libvirt
          group=kvm
          shell=/bin/false
          system=yes

    - name: ensure libvirt-dnsmasq system user is present
      user: >
          name=libvirt-dnsmasq
          uid=122
          home=/var/lib/libvirt/dnsmasq
          group=libvirtd
          shell=/bin/false
          system=yes

    - name: ensure nova system group is present
      group: >
          name=nova
          gid=123
          system=yes
  
    - name: ensure nova system user is present
      user: >
          name=nova
          uid=123
          home=/var/lib/nova
          group=nova
          groups=libvirtd
          shell=/bin/false
          system=yes

- name: OS Account(Identify)
  hosts: keystone
  sudo: yes

  tasks:
    - name: ensure keystone system group is present
      group: >
          name=keystone
          gid=124
          system=yes
  
    - name: ensure keystone system user is present
      user: >
          name=keystone
          uid=124
          home=/var/lib/keystone
          group=keystone
          shell=/bin/false
          system=yes

- name: OS Account(Image)
  hosts: glance
  sudo: yes

  tasks:
    - name: ensure glance system group is present
      group: >
          name=glance
          gid=125
          system=yes
  
    - name: ensure glance system user is present
      user: >
          name=glance
          uid=125
          home=/var/lib/glance
          group=glance
          shell=/bin/false
          system=yes

- name: OS Account(Volume)
  hosts: volume_scheduler:volume_backend:frontend
  sudo: yes

  tasks:
    - name: ensure cinder system group is present
      group: >
          name=cinder
          gid=126
          system=yes
  
    - name: ensure cinder system user is present
      user: >
          name=cinder
          uid=126
          home=/var/lib/cinder
          group=cinder
          shell=/bin/false
          system=yes

- name: OS Account(Network gateway)
  hosts: network_gateway
  sudo: yes

  tasks:
    - name: ensure neutron system group is present
      group: >
          name=neutron
          gid=127
          system=yes
  
    - name: ensure neutron system user is present
      user: >
          name=neutron
          uid=127
          home=/var/lib/neutron
          group=neutron
          shell=/bin/false
          system=yes
