---
- name: Open vSwitch (Network Gateway)
  hosts: network_gateway:compute_backend
  gather_facts: yes
  sudo: yes

  tasks:
    - name: ensure OVS kernel module is loaded
      modprobe: name=openvswitch state=present

    - name: ensure ovs bridge for gateway br-ex present
      openvswitch_bridge: bridge=br-{{my_data_if}} state=present
  
    - name: ensure br-ex has the external nic enslaved
      openvswitch_port: bridge=br-{{my_data_if}} port={{my_data_if}} state=present
