---
- name: OpenStack Networking (Frontend)
  hosts: frontend
  gather_facts: yes
  sudo: yes
  vars_files:
    - ../../program_vars/database_password
    - ../../program_vars/keystone_data
    - ../../program_vars/rabbitmq
    - ../../program_vars/neutron
    - ../../program_vars/neutron_metadata_key

  tasks:
    - name: ensure neutron-server and CLI packages are installed
      apt: pkg={{item}} force=yes
      with_items:
        - neutron-server
        - python-mysqldb
        - neutron-plugin-openvswitch
        - python-neutronclient
    
    - name: ensure ovs_neutron_plugin.ini file is configured
      template: >
            src=files/ovs_neutron_plugin.ini
            dest=/etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini
            owner=neutron group=neutron mode=0660 backup=yes
      notify:
        - restart neutron-server
    
    - name: ensure neutron.conf file is configured
      template: >
            src=files/neutron.conf
            dest=/etc/neutron/neutron.conf
            owner=neutron group=neutron mode=0660 backup=yes
      notify:
        - restart neutron-server
    
  handlers:
    - name: restart neutron-server
      service: name=neutron-server state=restarted
