---
- name: Common Setting(s)
  hosts: all
  sudo: yes

  tasks:
    - name: copy /etc/hosts
      copy: >
            src=files/hosts
            dest=/etc/hosts
            owner=root
            group=root
            mode=0644

    - name: some package is installed
      apt: pkg={{item}} force=yes
      with_items:
        - git
        - sysstat

    - name: ensure my.cnf file is configured
      copy: >
            src=files/sysstat_default
            dest=/etc/default/sysstat
            owner=root
            group=root
            mode=0644
      notify:
        - restart sysstat

  handlers:
    - name: restart sysstat
      service: name=sysstat state=restarted
