---
- name: Common Setting(s)
  hosts: network_gateway:compute_backend
  sudo: yes

  tasks:
    - name: some package is installed
      apt: pkg={{item}} force=yes
      with_items:
        - bridge-utils
        - vlan
