---
- name: Open vSwitch (Network Gateway)
  hosts: network_gateway
  gather_facts: yes
  sudo: yes

  tasks:
    - name: ensure openvswitch packages are installed
      apt: pkg={{item}} force=yes
      with_items:
        - openvswitch-common
        - openvswitch-switch
  
    - name: ensure OVS kernel module is loaded
      modprobe: name=openvswitch state=present

    - name: ensure ovs bridge for gateway br-ex present
      openvswitch_bridge: bridge=br-ex state=present
  
    - name: ensure br-ex has the external nic enslaved
      openvswitch_port: bridge=br-ex port={{my_ext_if}} state=present
  
    - name: ensure ipv6 on physical interface for br-ex is disabled
      sysctl: name=net.ipv6.conf.{{my_ext_if}}.disable_ipv6 value=1
  
    - name: ensure ipv6 on br-ex is disabled
      sysctl: name=net.ipv6.conf.br-ex.disable_ipv6 value=1
