---
- name: OpenStack Dashboard
  hosts: frontend
  sudo: yes
  vars_files:
    - ../../program_vars/keystone_data

  tasks:
    - name: ensure horizon packages are installed
      apt: pkg={{item}} update-cache=yes force=yes
      with_items:
        - memcached
        - openstack-dashboard
  
    - name: ensure horizon ubuntu packages is removed
      apt: pkg=openstack-dashboard-ubuntu-theme state=absent

    - name: ensure local_settings.py file is configured
      template: >
          src=files/local_settings.py
          dest=/etc/openstack-dashboard/local_settings.py
          owner=root
          group=root
          mode=0644
          backup=yes
      notify: restart services
  
  handlers:
    - name: restart services
      service: name={{item}} state=restarted
      with_items:
        - apache2
        - memcached
