---
- name: Apt Repositories
  hosts: all
  sudo: yes

  tasks:
    - name: ensure apt.conf is configured
      template: >
            src=files/apt.conf
            dest=/etc/apt/apt.conf
            owner=root
            group=root
            mode=0644
      when: "http_proxy is defined"
  
    - name: ensure ubuntu-cloud-keyring package is installed
      apt: pkg=ubuntu-cloud-keyring update_cache=yes
      
    - name: ensure python-pycurl package is installed
      apt: pkg=python-pycurl state=latest force=yes
  
    - name: ensure ubuntu-cloud-arvhive repository id added
      apt_repository: repo='deb http://ubuntu-cloud.archive.canonical.com/ubuntu precise-updates/havana main' state=present

    - name: ensure apt cache is updated
      apt: update_cache=yes
