---
- name: MySQL Server
  hosts: databases
  gather_facts: yes
  sudo: yes
  vars_files:
    - ../../program_vars/database_password

  tasks:
    - name: ensure .my.cnf file is configured
      template: >
            src=files/.my.cnf
            dest=/root/.my.cnf
            owner=root
            group=root
            mode=0600

    - name: ensure mysql-preseed file is created
      template: >
            src=files/mysql-server.seed
            dest=/root/mysql-server.seed
            owner=root
            group=root
            mode=0600

    - name: ensure mysql-server preseed is applied
      command: /usr/bin/debconf-set-selections /root/mysql-server.seed

    - name: ensure mysql-server and python-mysqldb installed
      apt: pkg={{item}} force=yes
      with_items:
        - mysql-server
        - python-mysqldb

    - name: ensure mysql-preseed file is removed
      file: path=/root/mysql-server.seed state=absent

    - name: ensure mysql debian-sys-maint password for localhost are altered
      mysql_user: >
            name=debian-sys-maint
            host=localhost
            password={{debian_db_password}}

    - name: ensure debian.cnf file is configured
      template: >
            src=files/debian.cnf
            dest=/etc/mysql/debian.cnf
            owner=root
            group=root
            mode=0600

    - name: ensure my.cnf file is configured
      copy: >
            src=files/my.cnf
            dest=/etc/mysql/my.cnf
            owner=root
            group=root
            mode=0664
      notify:
        - restart mysql

    - name: ensure anonymous users are not in the database
      mysql_user: >
            name=''
            host={{item}}
            state=absent
      with_items:
        - $ansible_hostname
        - 127.0.0.1
        - localhost

    - name: ensure test database is droped
      mysql_db: name=test state=absent

  handlers:
    - name: stop mysql
      service: name=mysql state=restarted

    - name: restart mysql
      service: name=mysql state=restarted
