---
- name: NTP Server
  hosts: frontend
  gather_facts: yes
  sudo: yes

  tasks:
    - name: ensure ntp package is installed
      apt: pkg=ntp force=yes
      when: "external_ntp_servers is defined"
  
    - name: ensure ntp.conf file is configured
      template: >
             src=files/ntp.server.conf
             dest=/etc/ntp.conf
             owner=root
             group=root
             mode=0644
      notify: restart ntp
      when: "external_ntp_servers is defined"
  
  handlers:
    - name: restart ntp
      service: name=ntp state=restarted

- name: NTP Client
  hosts: all:!frontend
  sudo: yes

  tasks:
    - name: ensure ntp package is installed
      apt: pkg=ntp force=yes
      when: "internal_ntp_servers is defined"
  
    - name: ensure ntp.conf file is configured
      template: >
             src=files/ntp.client.conf
             dest=/etc/ntp.conf
             owner=root
             group=root
             mode=0644
      notify: restart ntp
      when: "internal_ntp_servers is defined"
  
  handlers:
    - name: restart ntp
      service: name=ntp state=restarted
