- include: playbooks/apt/main.yml
- include: playbooks/common/main.yml
- include: playbooks/os_account/main.yml
- include: playbooks/ovs_int/main.yml
- include: playbooks/ovs_ext/main.yml
- include: playbooks/ovs_data/main.yml
- include: playbooks/mysql/main.yml
- include: playbooks/ntp/main.yml
- include: playbooks/keystone/main.yml
- include: playbooks/rabbitmq/main.yml
- include: playbooks/memcached/main.yml
- include: playbooks/glance/main.yml
- include: playbooks/cinder/main.yml
- include: playbooks/neutron/main.yml
- include: playbooks/nova/main.yml
- include: playbooks/horizon/main.yml
